# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: debug-statements
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.13.0
  hooks:
  - id: reorder-python-imports
    args: [--add-import, 'from __future__ import annotations']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
  # Run the linter
  - id: ruff
    args: [ --fix ]
  # Run the formatter
  - id: ruff-format

# Not suitable for now, config is not read!
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.11.2
#   hooks:
#   - id: mypy
#     files: (eschergraph/|tests/|scripts/)
#     exclude: |
#       eschergraph/tools/pdf_document_layout_analysis/|
#       eschergraph/tools/fast_pdf_parser/parser.py
#     additional_dependencies: [attrs, jinja2, openai, tenacity, pytest, types-assertpy, types-requests]
#     args: [--config=pyproject.toml]