from __future__ import annotations

DEFAULT_SAVE_LOCATION: str = "./eschergraph_storage"
DEFAULT_GRAPH_NAME: str = "escher_default"
COMMUNITY_TEMPLATE: str = "community_prompt.jinja"
TEMPLATE_IMPORTANCE: str = "search/importance_rank.jinja"
JSON_BUILD: str = "json_build.jinja"
JSON_PROPERTY: str = "json_property.jinja"
JSON_TABLE: str = "json_table.jinja"
JSON_KEYWORDS: str = "json_keywords.jinja"
JSON_FIGURE: str = "json_figure.jinja"
SUMMARY: str = "summary.jinja"
TOPIC_EXTRACTION: str = "main_topics.jinja"
TOPIC_RELATIONS: str = "topic_relations.jinja"
MAIN_COLLECTION: str = "main_collection"
GLOBAL_SEARCH_TEMPLATE: str = "search/global_search_context.jinja"
